accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("userdelete/", views.userdelete, name="userdelete"),
    path("userupdate/", views.userupdate, name="userupdate"),
    path("password/", views.password, name="password"),
]
    

articles/urls.py
from django.urls import path
from . import views


app_name = "articles"

urlpatterns = [

    path('',views.articles, name="articles"),
    path("create/",views.create, name="create"),

    path("<int:pk>/",views.detail, name= "detail"),
    path("<int:pk>/delete/",views.delete, name = "delete"),
    path("<int:pk>/update/",views.update, name = "update"),
    path("<int:pk>/comments/",views.comment_create, name = "comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/", views.comment_delete, name="comment_delete",),
    path("<int:pk>/like/", views.like, name="like"),


    path('index/',views.index, name= "index"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    
    path("articles/",include("articles.urls")),
    path("users/",include("users.urls")),
    path("accounts/", include("accounts.urls")),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("",views.users, name="users"),
    path("profile/<str:username>/", views.profile,name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),


    
]

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length= 50)
    content = models.TextField()
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    image = models.ImageField(upload_to="images/", blank=True)

    author = models.ForeignKey(
				settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles")

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    
    content = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ("author",)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ("article", "user")

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods



# Create your views here.
def index(request):
    return render(request, "articles/index.html")

def articles(request):
    articles = Article.objects.all().order_by("-created_at")
    context = {
        "articles":articles,
        }
    return render(request, "articles/articles.html", context)

def detail(request,pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comments.all().order_by("-pk")
    context = {
        "article" : article,
        "comment_form" : comment_form,
        "comments": comments,
    }
    return render(request, "articles/detail.html",context)

@login_required
def create(request):

    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm()

    context = { "form" : form }
    return render(request, "articles/create.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if article.author == request.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect("articles:detail", article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect("articles:articles")

    context = {
        "form": form,
        "article": article,
    }
    return render(request, "articles/update.html", context)



@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user.is_authenticated:
        if article.author == request.user:
            article = get_object_or_404(Article, pk=pk)
            article.delete()
    return redirect("articles:articles")

@require_POST
def comment_create(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect("articles:detail", article.pk)

    

@require_POST
def comment_delete(request, pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
    return redirect("articles:detail", pk)

@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
        else:
            article.like_users.add(request.user)
    
        return redirect("articles:articles")

    return redirect("accounts:login")

articles/templates/articles/articles.html
{% extends 'base.html' %}
{% block content %}
    <h2>Articles</h2>

    {% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}">
        <button>새로운 글 작성</button>
    </a>
    {% else %}
    <a href="{% url 'accounts:login' %}">로그인하고 작성하기</a>

    {% endif %}

    {% for article in articles %}
        <a href="{% url 'articles:detail' article.pk %}">
            <p>[{{article.pk}}] {{ article.title }}</p>
        </a>
        <form action="{% url 'articles:like' article.pk %}" method = "POST">
            {% csrf_token %}
            {% if request.user in article.like_users.all %}
                <button class="btn btn-link">
                    <i class="fa-solid fa-thumbs-up"></i>
                </button>
                
            {% else %}
                <button class="btn btn-link">
                    
                    <i class="fa-regular fa-thumbs-up"></i>
                </button>
                
            {% endif%}
        </form>
        
    {% endfor %}
{% endblock content %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Article</h1>
    <form action="{% url 'articles:create'%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
 
        <button type="submit">
            저장
        </button>
    </form>
    <a href="{% url 'articles:articles' %}">목록</a>
    

{% endblock content %}

articles/templates/articles/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <h2>글 상세 페이지</h2>
    <p>제목: {{ article.title }}</p>
    <p>
        작성자: 
        <a href="{% url 'users:profile' article.author.username %}" class="btn btn-primary">
            {{ article.author.username }}
        </a>
    </p>
    {% if article.image %}
        <img src="{{ MEDIA_URL }}{{ article.image.url }}" >
    {% endif %}
    <p>내용: {{ article.content }}</p>
    <p>가격: {{ article.price }}원</p>
    <p>작성일시: {{ article.created_at }}</p>
    <p>수정일시: {{ article.updated_at }}</p>

    <a href="{% url 'articles:articles' %}">목록 보기</a><br>
    {% if user == article.author %}
        <a href="{% url 'articles:update' article.pk %}">
            <button>수정하기</button>
        </a>

        <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    {% endif %}
    
    {% if request.user.is_authenticated %}
    <br>
    <hr>
    <h3>댓글 {{ comments|length }}개</h3>
    <form action="{% url "articles:comment_create" article.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="댓글작성">
    </form>
    {% endif %}

    {% for comment in comments %}
    <ul>
        <li>{{ comment.content }} - {{ comment.user.username }}</li>

        {% if user == comment.user %}
        <form action="{% url 'articles:comment_delete' article.pk comment.pk%}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
        {% endif %}
        
    </ul>

    {% empty %}
    <p>댓글이 없습니다.</p>

    {% endfor %}

{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>INDEX PAGE</h1>

    <img src="{% static 'articles/market.png' %}">
    <ul>
        <li><a href="{% url 'articles:articles' %}">목록 보기</a></li>
        <li><a href="{% url 'users:users' %}">Users 이동</a></li>
    </ul>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% block content %}
    <h1>edit Article</h1>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">
        수정
        </button>
    </form>
    <a href="{% url 'articles:detail' article.pk %}">이전</a>
{% endblock content %}