articles/urls.py
from django.urls import path
from . import views


app_name = "articles"

urlpatterns = [

    path('',views.articles, name="articles"),
    path("create/",views.create, name="create"),

    path("<int:pk>/",views.detail, name= "detail"),
    path("<int:pk>/delete/",views.delete, name = "delete"),
    path("<int:pk>/update/",views.update, name = "update"),
    path("<int:pk>/comments/",views.comment_create, name = "comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/", views.comment_delete, name="comment_delete",),
    path("<int:pk>/like/", views.like, name="like"),


    path('index/',views.index, name= "index"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    
    path("articles/",include("articles.urls")),
    path("users/",include("users.urls")),
    path("accounts/", include("accounts.urls")),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("",views.users, name="users"),
    path("profile/<str:username>/", views.profile,name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),


    
]

users/models.py
from django.conf import settings
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='following_profiles', blank=True)  # 팔로워
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='follower_profiles', blank=True)  # 팔로우

    def __str__(self):
        return self.user.username

users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from articles.models import Article 
from .models import Profile


def users(request):
    return render(request, "users/users.html")

# Create your views here.

def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    liked_articles = member.like_articles.all()
    authored_articles = Article.objects.filter(author=member)
    
    context = {
        "member" : member,
        "liked_articles": liked_articles,
        "authored_articles": authored_articles,
        
    }
    return render(request, "users/profile.html", context)

@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member != request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", username=member.username)    
    return redirect("accounts:login")

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ member.username }}의 프로필 페이지</h1>

    <div>
        <h2>이름 : {{ member.username }}</h2>
        <h3>가입일: {{ member.date_joined|date:"Y년 m월 d일" }}</h3>


    

        {% if liked_articles %}
            <h3>찜한 글 목록:</h3>
            <ul>
                {% for article in liked_articles %}
                    <li>
                        <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>찜한 글이 없습니다.</p>
        {% endif %}

        {% if authored_articles %}
            <h3>작성한 글 목록:</h3>
            <ul>
                {% for article in authored_articles %}
                    <li>
                        <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>작성한 글이 없습니다.</p>
        {% endif %}

        {% if request.user != member %}
            <form action="{% url 'users:follow' member.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in member.followers.all %}
                    <input type="submit" value="언팔로우">
                {% else %}
                    <input type="submit" value="팔로우">
                {% endif %}


            </form>
        {% endif %}
    </div>

    <a href="/index/">홈으로 돌아가기</a>

{% endblock content %}

users/templates/users/users.html
{% extends 'base.html' %}

{% block content %}
    <h1>Test</h1>
    <a href="{% url 'articles:index' %}">Index 이동</a>
{% endblock content %}