accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("userdelete/", views.userdelete, name="userdelete"),
    path("userupdate/", views.userupdate, name="userupdate"),
    path("password/", views.password, name="password"),
]
    

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from articles import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    
    path("articles/",include("articles.urls")),
    path("users/",include("users.urls")),
    path("accounts/", include("accounts.urls")),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("",views.users, name="users"),
    path("profile/<str:username>/", views.profile,name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),


    
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/61fc22ac73.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>


    {% block head %}{% endblock head %}
</head>
<body>

    <div class="navbar">
        {% if request.user.is_authenticated %}
        <h3>안녕 {{ request.user.username }}</h3>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃"></input>
        </form>

        <a href="{% url 'accounts:userupdate' %}">회원 정보 수정</a>
        

        <form action="{% url 'accounts:userdelete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="회원 탈퇴"></input>
        </form>

        {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원 가입</a>

        {% endif %}


        
    </div>
        
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>